### ISSUE TITLE
Functionality to open in new tab

### ISSUE THREAD

**Issue by yenicelik** [jaketrent/react-social-icons#104]
Is there any functionality to open the link in a new tab, rather than redirecting in the current tab?

**Comment by couetilc** [comment]
@yenicelik the root html element of the `<SocialIcon />` component is an [anchor](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) element. Simply pass a prop "target" to the component in order to control the [anchor tag's target attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target)

Specifically for you,
```js
<SocialIcon target="_blank" /> // on click, opens in new tab or window
```
