### ISSUE TITLE
Hydration error when used with Next's Link component

### ISSUE THREAD

**Issue by javadrip** [jaketrent/react-social-icons#153]
I've isolated the issue to this part of my code (removed some CSS for simplicity):
```
import { SocialIcon } from "react-social-icons";
import Link from "next/link";

<Link href="#contact">
   <SocialIcon
      className="cursor-pointer"
      network="email"
      fgColor="#245F7F"
      bgColor="transparent"
  />
  <p>
     Get in touch
  </p>
</Link>
```

Wrapping `SociaIcon` in Next's `Link` component in this way resulted in this error:

> Warning: validateDOMNesting(...): `<a>` cannot appear as a descendant of `<a>`.

When I commented out the SocialIcon component, everything loaded fine without errors.

And when I tried to load it along with the whole website, 3 unhandled runtime errors (two of which were the same) popped up:

1. Hydration failed because the initial UI does not match what was rendered on the server. (two counts of this particular error)
2. There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.

Did I do anything wrong? If so, how can I resolve this?

**Comment by couetilc** [comment]
The `<SocialIcon>` component _is_ an `<a>` tag, so if `<Link>` is an `<a>` too then they nest and cause your error message. 

To quickly fix your issue: do _not_ use the `<Link>` component, it's unnecessary because you are doing a hash navigation to `#contact` (your page will not reload, just scroll, here's a page with some detail about this https://developer.chrome.com/docs/web-platform/navigation-api/#scroll-handling). Instead, use `<SocialIcon url="#contact" network="email"><p>Get in touch</p><SocialIcon>` alone, with any appropriate styling. That should get rid of the error message and preserve your functionality.

As of now, there is no option to change the base component type of the `<SocialIcon>` component, I may add that soon in the future, and another issue when using it with the Next.js link component is that it does not forward refs. I will fix that in the future but will probably be in a new major version.

**Comment by javadrip** [comment]
Thanks for replying! I'll try that.

**Comment by javadrip** [comment]
Reporting back after trying @couetilc's suggestion: It was successful! 

Thank you @couetilc!
