### ISSUE TITLE
What's the best way to make these rounded square instead of circle?

### ISSUE THREAD

**Issue by mledwards** [jaketrent/react-social-icons#66]
What's the best way to make these rounded square instead of circle?

**Comment by couetilc** [comment]
Each rendered SocialIcon svg has a class name "social-svg" which you can use to override the [border-radius](https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius) css prop.

For example, include this in your stylesheet to make all the icons on your page square:
```
.social-svg {
  border-radius: 0 !important;
}
```

`!important` is added because border-radius is specified by an inline style on the svg element.

**Comment by mledwards** [comment]
Thanks! 👍
